/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    // add paths according to your project structure
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "secondary-fixed": "#ede1d4",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#574236",
        "on-primary": "#ffffff",
        "secondary-container": "#ede1d4",
        "inverse-on-surface": "#f3f0eb",
        "on-secondary-fixed-variant": "#4d463d",
        "on-secondary-container": "#6b6359",
        "on-background": "#1c1c19",
        "primary-container": "#b9b4af",
        "surface-dim": "#dcdad5",
        "inverse-primary": "#cbc5c1",
        "surface-container-low": "#f6f3ee",
        "on-surface": "#1c1c19",
        "outline-variant": "#d0c5bb",
        "on-secondary-fixed": "#201b13",
        "surface-bright": "#fcf9f4",
        "surface-tint": "#625e5a",
        "surface-container-highest": "#e5e2dd",
        "on-primary-fixed-variant": "#4a4643",
        secondary: "#655d54",
        "tertiary-fixed": "#fcdccb",
        "secondary-fixed-dim": "#d0c5b9",
        "tertiary-fixed-dim": "#dfc0b0",
        "on-error": "#ffffff",
        "on-primary-container": "#494642",
        background: "#fcf9f4",
        "tertiary-container": "#ccaf9f",
        "primary-fixed": "#e8e1dd",
        tertiary: "#715a4c",
        "on-surface-variant": "#4d453e",
        "surface-variant": "#e5e2dd",
        surface: "#fcf9f4",
        "primary-fixed-dim": "#cbc5c1",
        outline: "#7e756e",
        "surface-container-high": "#ebe8e3",
        "surface-container": "#f0ede9",
        "on-tertiary-fixed": "#28180e",
        "error-container": "#ffdad6",
        primary: "#625e5a",
        "on-tertiary-container": "#574235",
        "inverse-surface": "#31302d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1e1b18",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};